---
title: "Practice_L3"
author: "WuJuHsiung"
date: "2021/11/29"
output: html_document
---

# Create the *Lotka-Volterra* equations
```{r}
grow <- function(start_1, start_2){
  num_gen <- 30
  N1 <- rep(0, num_gen)
  N2 <- rep(0, num_gen)
  generation <- rep(1, num_gen)
  growth.rate_1 <- 1.2
  growth.rate_2 <- 1.2
  K1 <- 100
  K2 <- 120
  a12 <- 0.8
  a21 <- 0.8
  N1[1] <- start_1
  N2[1] <- start_2
  
  for(i in 2:num_gen){
    N1[i] = N1[i-1] + (growth.rate_1 * N1[i-1] * (K1 - N1[i-1] - a12 * N2[i-1]) / K1)
    N2[i] = N2[i-1] + (growth.rate_2 * N2[i-1] * (K2 - N2[i-1] - a21 * N1[i-1]) / K2)
    
    generation[i] = i
  }

  if(N1[1] > 0){
    plot(N1 ~ generation, typ = "o", ylim = c(0, max(c(K1, K2))), 
         ylab = "N", sub = paste("N1 =", start_1, ", N2 =", start_2))
    legend("right", legend = c("N1", "N2"), col = c(1, 2), pch = 1, bty = "o")
  } 
  else{
    plot(N1 ~ generation, typ = "o", ylim = c(0, max(c(K1, K2))), 
         ylab = "N", sub = paste("N1 =", start_1, ", N2 =", start_2))
  }
  
  if(N2[1] > 0){
    lines(N2 ~ generation, typ = "o", col = 2)
    legend("right", legend = c("N1", "N2"), col = c(1, 2), pch = 1, bty = "o")
  }
}
```

# Create plots
```{r}
par(mar = c(5, 4, 1, 1), mfrow = c(3, 1), las = 1)

grow(1, 0)
text(2, 110, "Species 1 alone")

grow(0, 1)
text(2, 110, "Species 2 alone")

grow(1, 2)
text(3, 110, "Both species competing")
```
